### ISSUE TITLE
New MSS

### ISSUE THREAD

**Issue by EVanElverdinghe** [CVidalG/Index-of-Armenian-Manuscripts#3]
ID|Location|Country|Permalink|Digital Library|Support|Date|Pages|Size|Title
---|---|---|---|---|---|---|---|---|---
MUC T. Schweiger cod_man_002|Tassilo Schweiger|Germany|https://katalog.altes-buch.de/handschriften.php|altes-buch.de|Paper|18th-19th century?|434 pages|in-12|?
NH Syriac MS 9|Beinecke Rare Book and Manuscript Library|USA|https://collections.library.yale.edu/catalog/2052914|Yale University Library Digital Collections|Paper|?|288 pages|?|Syriac-Armenian Lexicon
OSL 1776/05|The Schøyen Collection|Norway and UK|https://www.schoyencollection.com/palaeography-collection-introduction/latin-book-scripts/east-european-book-scripts/armenian-erkata-gir/ms-1776-05|The Schøyen Collection|Parchment|12th century|1 image|27 × 18 cm|Prayer book / Arabian Nights
PHM 1945‑65‑20|Philadelphia Museum of Art, Department of Prints, Drawings, and Photographs|USA|https://bibliophilly.library.upenn.edu/viewer.php?id=1945‑65‑20|BiblioPhilly|Parchment|16th century|253 folios|11.0 × 7.8 cm|Liturgical psalter and perpetual calendar
PHM 1953‑128‑7|Philadelphia Museum of Art, Department of Prints, Drawings, and Photographs|USA|https://bibliophilly.library.upenn.edu/viewer.php?id=1953‑128‑7|BiblioPhilly|Parchment|early 16th century|248 folios|12.0 × 9.0 cm|Liturgical psalter
PHX LJS 443|University of Pennsylvania, Kislak Center for Special Collections, Rare Books and Manuscripts|USA|http://bibliophilly.library.upenn.edu/viewer.php?id=LJS 443|BiblioPhilly|Paper|1416 or later|258 folios|18.6 × 13.5 cm|Collection of texts on the calendar
SAAB Cod. Sang. 1513|St. Gallen, Stiftsbibliothek|Switzerland|http://e-codices.unifr.ch/en/list/one/csg/1513|e-codices|Paper|XLV+131 pages|34.0 × 16.5 cm|Confessio fidei Armenicæ ecclesiæ

**Comment by CVidalG** [comment]
Thanks @EVanElverdinghe ! Update done
Can't succeed to access to PHX LJS 443, and should we include SAAB Cod. Sang. 1513 in the list (not really a manuscript) ?
