### ISSUE TITLE
Newly-digitized MSS in Italy

### ISSUE THREAD

**Issue by EVanElverdinghe** [CVidalG/Index-of-Armenian-Manuscripts#6]
ID|Location|Country|Permalink|Digital Library|Support|Date|Pages|Size|Title
---|---|---|---|---|---|---|---|---|---
FLL Or. 465|Biblioteca Medicea Laurenziana|Italy|https://tecabml.contentdm.oclc.org/digital/collection/orientali/id/26602|BML Digital Library|Paper|s.d.|242 folios|200 x 260 mm|Composito . Parte di calendario armeno. Frammenti di breviario armeno. Salmi siriaci, raccolta parziale
FLL Plut. 1.11|Biblioteca Medicea Laurenziana|Italy|https://tecabml.contentdm.oclc.org/digital/collection/plutei/id/258650|BML Digital Library|Paper|s.d.|279 folios|155 x 240 mm|Evangelia quatuor, Marcus, Matthaeus, Lucas, et Ioannes . Evangelia literis, ac lingua Armena
FLL Plut. 1.13|Biblioteca Medicea Laurenziana|Italy|https://tecabml.contentdm.oclc.org/digital/collection/plutei/id/338520|BML Digital Library|Parchment|1353|428 folios|155 x 240 mm|Missale in idiomate Armeno scriptum anno Dom. 1353 ab archiepiscopo Armeno Ord. Praedicatorum . Missale Armenum ex Lat. traductum ab episcopo Gregorio anno 1353. [...] Ab initio calendarium habet, ad nostram rationem emendatum
FLL Plut. 1.62|Biblioteca Medicea Laurenziana|Italy|https://tecabml.contentdm.oclc.org/digital/collection/plutei/id/163137|BML Digital Library|Parchment|1701-1800|23 folios|137 x 190 mm|Messale
FLL Plut. 1.63|Biblioteca Medicea Laurenziana|Italy|https://tecabml.contentdm.oclc.org/digital/collection/plutei/id/183165|BML Digital Library|Parchment|1701-1800|263 folios|200 x 305 mm|Messale
VAT Arch.Cap.S.Pietro.B.77|Biblioteca Apostolica Vaticana|Vatican City|https://digi.vatlib.it/view/MSS_Arch.Cap.S.Pietro.B.77|DigiVatLib|NaN|NaN|NaN|NaN|NaN
VAT Arch.Cap.S.Pietro.F.39|Biblioteca Apostolica Vaticana|Vatican City|https://digi.vatlib.it/view/MSS_Arch.Cap.S.Pietro.F.39|DigiVatLib|NaN|NaN|NaN|NaN|NaN

**Comment by CVidalG** [comment]
Thanks!
