### ISSUE TITLE
New digital MSS

### ISSUE THREAD

**Issue by EVanElverdinghe** [CVidalG/Index-of-Armenian-Manuscripts#7]
ID|Location|Country|Permalink|Digital Library|Support|Date|Pages|Size|Title
---|---|---|---|---|---|---|---|---|---
ATB ΓΕ 35033|Benaki Museum|Greece|[See manuscript](https://www.benaki.org/index.php?option=com_collectionitems&view=collectionitem&id=160304)|NaN|Paper|1581|237 folios|27 x 18 cm|Τὰ τέσσερα Εὐαγγέλια
CBU Oo. 1.1,2|Cambridge University Library|UK|[See manuscript](https://cudl.lib.cam.ac.uk/view/MS-OO-00001-00001)|University of Cambridge Digital Library|NaN|Probably the end of the 12th century|323 folios|44 x 28 cm|Buchanan Bible
CD Arm. 11|Houghton Library, Harvard University|USA|[See manuscript](https://iiif.lib.harvard.edu/manifests/view/drs:500005072)|Harvard Library|NaN|1643|661 images|NaN|Gospels
MAN 8560|Biblioteca Nacional de España|Spain|[See manuscript](https://bdh-rd.bne.es/viewer.vm?id=0000072310)|Biblioteca Digital Hispánica|NaN|NaN|107 images|NaN|Liturgia armenia
NaN|Museum of the Bible|USA|[See manuscript](https://collections.museumofthebible.org/artifacts/42501-gospels-of-matthew-and-john-with-canon-tables)|Museum of the Bible Collections|Vellum|ca. 1040|9 folios|16.5 × 11.8 in. (42.0 × 30.0 cm)|Gospels of Matthew and John with Canon Tables
OSL 575|The Schøyen Collection|Norway and UK|[See manuscript](https://www.schoyencollection.com/patristic-literature-collection/ms-575)|The Schøyen Collection|Vellum|501-600|18 folios|23 x 17 cm|Codex Armenicus Rescriptus (Johannes Chrysostomus: Homilies on the Psalter)
OSL 2082|The Schøyen Collection|Norway and UK|[See manuscript](https://www.schoyencollection.com/palaeography-collection-introduction/latin-book-scripts/east-european-book-scripts/armenian-bolorgir/ms-2082)|The Schøyen Collection|Paper|1721|30 folios|24 x 18 cm|Archbishop Mouses Missal

**Comment by CVidalG** [comment]
Thank you @EVanElverdinghe! It will be soon online.
It seems that most of these manuscripts are not available online, only the cover page? I am wondering if we should include them. Perhaps with a tag "ressource not available"?

**Comment by EVanElverdinghe** [comment]
That's true. I agree that ATB ΓΕ 35033, OSL 575, and OSL 2082 actually shouldn't be included at all.
